#!/usr/bin/R

p1 <- ggplot(a1,aes(x=pos,y=lai,color=id)) + geom_line() + xlim(0,208) + scale_color_brewer(palette = "Set2") + theme_bw() + theme(panel.background = element_blank(),axis.text.x = element_blank(),legend.position = "none",axis.title.y = element_blank()) + xlab("Chr01")+ylim(0,40)
p2<- ggplot(a2,aes(x=pos,y=lai,color=id)) + geom_line()  + scale_color_brewer(palette = "Set2") + theme_bw() + theme(panel.background = element_blank(),axis.text.x = element_blank(),legend.position = "none",axis.title.y = element_blank(),axis.text.y = element_blank()) + xlab("Chr02")+ xlim(0,255)+ylim(0,40)
p3 <-  ggplot(a3,aes(x=pos,y=lai,color=id)) + geom_line()  + scale_color_brewer(palette = "Set2") + theme_bw() + theme(panel.background = element_blank(),axis.text.x = element_blank(),legend.position = "none",axis.title.y = element_blank(),axis.text.y = element_blank()) + xlab("Chr03")+ xlim(0,266)+ylim(0,40)
p4<-  ggplot(a4,aes(x=pos,y=lai,color=id)) + geom_line()  + scale_color_brewer(palette = "Set2") + theme_bw() + theme(panel.background = element_blank(),axis.text.x = element_blank(),legend.position = "none",axis.title.y = element_blank(),axis.text.y = element_blank()) + xlab("Chr04")+ xlim(0,260)+ylim(0,40)
p5 <- ggplot(a5,aes(x=pos,y=lai,color=id)) + geom_line()  + scale_color_brewer(palette = "Set2") + theme_bw() + theme(panel.background = element_blank(),axis.text.x = element_blank(),axis.title.y = element_blank(),axis.text.y = element_blank()) + xlab("Chr05")+ xlim(0,258)+ylim(0,40)
p6<-  ggplot(a6,aes(x=pos,y=lai,color=id)) + geom_line()  + scale_color_brewer(palette = "Set2") + theme_bw() + theme(panel.background = element_blank(),axis.text.x = element_blank(),legend.position = "none",axis.title.y = element_blank()) + xlab("Chr06")+ xlim(0,255)+ylim(0,40)
p7 <- ggplot(a7,aes(x=pos,y=lai,color=id)) + geom_line()  + scale_color_brewer(palette = "Set2") + theme_bw() + theme(panel.background = element_blank(),axis.text.x = element_blank(),legend.position = "none",axis.title.y = element_blank(),axis.text.y = element_blank()) + xlab("Chr07")+ xlim(0,214)+ylim(0,40)
p8 <- ggplot(a8,aes(x=pos,y=lai,color=id)) + geom_line()  + scale_color_brewer(palette = "Set2") + theme_bw() + theme(panel.background = element_blank(),axis.text.x = element_blank(),legend.position = "none",axis.title.y = element_blank(),axis.text.y = element_blank()) + xlab("Chr08")+ xlim(0,172)+ylim(0,40)
p9<- ggplot(a9,aes(x=pos,y=lai,color=id)) + geom_line()  + scale_color_brewer(palette = "Set2") + theme_bw() + theme(panel.background = element_blank(),axis.text.x = element_blank(),legend.position = "none",axis.title.y = element_blank(),axis.text.y = element_blank()) + xlab("Chr09")+ xlim(0,204)+ylim(0,40)
pX <- ggplot(aX,aes(x=pos,y=lai,color=id)) + geom_line()  + scale_color_brewer(palette = "Set2") + theme_bw() + theme(panel.background = element_blank(),axis.text.x = element_blank(),axis.title.y = element_blank(),axis.text.y = element_blank()) + xlab("Chr0X")+ xlim(0,276)+ylim(0,40)

p1 + p2 +p3 +p4 +p5 +p6 +p7 +p8+p9+pX + plot_layout(nrow = 2,byrow = T)
